### ISSUE TITLE
Melee damage error

### ISSUE THREAD

**Issue by bendgame** [gregparkes/WebBattleSim#1]
I was noticing the simulation stopping unexpectedly when using Jedi and checked the console to see this error:

melee.js:14 Uncaught TypeError: Cannot read properties of undefined (reading 'dealDamageFrom')
    at Object.damage_unit [as func] (melee.js:14)
    at Object.update (event.js:21)
    at Melee.update (melee.js:21)
    at update_f (battle.js:169)
    at Array.forEach (<anonymous>)
    at Object.update (battle.js:180)
    at animate_loop (win_canvas.js:220)

**Comment by bendgame** [comment]
I believe the issue is fixed by adjusting the last line in this:

constructor(source, damage, target) {
        // call constructor of attack
        super(source, damage, false);
        this.target = target;
        this.e = EventDelay(this.damage_unit, 0.5, 1);
    }

should be this, I think: 
this.e = EventDelay(this.damage_unit(), 0.5, 1); 

without the (), the target becomes undefined, hence the error in console.

**Comment by gregparkes** [comment]
Hi @bendgame,

Apologies for not reading this sooner - I apparently didn't have notifications enabled

This bug has now been fixed - thank you for the suggestion.
